### ISSUE TITLE
Pre-MVP business requirements discussion

### ISSUE THREAD

**Issue by ruiccarvalho** [Cineclub/cineclub#32]
### General
- Register users & provide usual actions (ch./reset password)
- Dashboard with access to application's functions

### App logic (still no automation)

- [x] A user can join or leave any team from all the teams that exist, or create a new one. Still no invitation logic, assume well-behaved users.
- [x] In the context of a team, a user can create a new round (either if there already exists any or it's the first one)
- [ ] ~Any user, in any of their teams (later, we'll enforce a fairness rule, but for now let's do it like this), can pick *THE* movie for that round. There's only one, we may or may not allow to replace; up to debate.~ [In the MVP checklist issue #53]
- [x] Users of the team can mark the active round's movie as seen (by adding a "screening")

**Comment by gdiasdasilva** [comment]
Looks good to me. Let's split those bullets into different issues (and pull requests).

**Comment by gdiasdasilva** [comment]
Implementing **In the context of a team, a user can create a new round (either if there already exists any or it's the first one)** in #38.

**Comment by gdiasdasilva** [comment]
**Users of the team can mark the active round's movie as seen (by adding a "screening")** implemented in #41.
